disabled_rules:
- colon
- trailing_newline
- trailing_whitespace
- line_length
- identifier_name

- force_cast
- function_parameter_count
- force_try
- class_delegate_protoco
- todo
- redundant_string_enum_value
- redundant_optional_initialization
- class_delegate_protocol
- weak_delegate
- function_body_length
- cyclomatic_complexity
- type_body_length
- file_length
excluded:
- Pods
